"""empty message

Revision ID: 2cecea8ea55c
Revises: 478d1735a6a6
Create Date: 2015-05-29 14:42:07.117227

"""

# revision identifiers, used by Alembic.
revision = '2cecea8ea55c'
down_revision = '478d1735a6a6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('sys_notification',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('msg', sa.String(length=255), nullable=True),
    # sa.Column('create_time', sa.TIMESTAMP(), nullable=True),
    # sa.Column('end_time', sa.TIMESTAMP(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_unique_constraint(None, 'users', ['email'])
    # op.create_unique_constraint(None, 'users', ['username'])
    ### end Alembic commands ###
    pass


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users')
    op.drop_constraint(None, 'users')
    op.drop_table('sys_notification')
    ### end Alembic commands ###
