"""add EmailTemplate model

Revision ID: a4c4dec8fdc
Revises: 84effddd3d0
Create Date: 2015-05-31 15:37:17.220458

"""

# revision identifiers, used by Alembic.
revision = 'a4c4dec8fdc'
down_revision = '84effddd3d0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('email_templates',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(length=150), nullable=True),
    # sa.Column('template_content', sa.Text(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_unique_constraint(None, 'users', ['email'])
    # op.create_unique_constraint(None, 'users', ['username'])
    ### end Alembic commands ###
    pass


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'users')
    #op.drop_constraint(None, 'users')
    #op.drop_table('email_templates')
    ### end Alembic commands ###
    pass
